{"name": "test_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == False", "trace": "def test_03():\n>       assert 1 == False\nE       assert 1 == False\n\ntests\\parallel\\test_parallel.py:13: AssertionError"}, "start": 1703777586877, "stop": 1703777586878, "uuid": "715b50e9-e1b1-4f97-a953-8af2f038113d", "historyId": "9bb13bfa3576f62114c363b26803d0ee", "testCaseId": "9bb13bfa3576f62114c363b26803d0ee", "fullName": "tests.parallel.test_parallel#test_03", "labels": [{"name": "parentSuite", "value": "tests.parallel"}, {"name": "suite", "value": "test_parallel"}, {"name": "host", "value": "DESKTOP-NPC46QP"}, {"name": "thread", "value": "7968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.parallel.test_parallel"}]}